export enum UserReducerEnum {
  FOLLOW = 'USERS/FOLLOW',
  UNFOLLOW = 'USERS/UNFOLLOW',
  SET_USERS = 'USERS/SET-USERS',
  SET_FILTER = 'USERS/SET-FILTER',
  SET_CURRENT_PAGE = 'USERS/SET-CURRENT-PAGE',
  SET_TOTAL_USERS_COUNT = 'USERS/SET-TOTAL-USERS-COUNT',
  TOGGLE_IS_FETCHING = 'USERS/TOGGLE-IS-FETCHING',
  TOGGLE_FOLLOWING_PROGRESS = 'USERS/TOGGLE-FOLLOWING-PROGRESS',
}